name: Build and unit test

on: [push, pull_request]
  #push:
   # branches: [ workflow ]
#    branches: [ master ]  
#  pull_request:
#    branches: [ master ]
jobs:
  build:
 
    runs-on: windows-latest

    strategy:
      matrix:
        targetplatform: [x64]

    env:
      SigningCertificate: GitHubActionsDemo.pfx
      Solution_Path: Create-List-WPF.sln
#      Test_Project_Path: Create-List-WPF.Tests\Create-List-WPF.Tests.csproj
#      Wpf_Project_Path: Create-List-WPF\Create-List-WPF.csproj
#      Wap_Project_Directory: Create-List-WPF.Package
#      Wap_Project_Name: Create-List-WPF.Package.wapproj
  
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name:  Setup .NET Core 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'      
            
  
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    
    - name: Restore nuget
      run: nuget restore $env:Solution_Path
      
      # Build the Windows Application Packaging project
    - name: Build the Windows Application Packaging Project (wapproj) 
      run: msbuild $env:Solution_Path 
      
   
      
    - name: NUnit 
      run: dotnet test $env:Solution_Path
